### ISSUE TITLE
suggestion for the demo

### ISSUE THREAD

**Issue by neal1991** [wangdahoo/vswipe#2]
Just a suggestion, utilize a github page to display the demo instead of using https://github.com/wangdahoo/vswipe/blob/master/examples/index.html directly.

**Comment by wangdahoo** [comment]
Currently, I use `docs/` for github-pages, and more use cases will be updated here later. The `index.html` is only a simple reference for beginner, as you know, the example in `README.md` is just a pattern of *.vue file. Any way, thanks for suggestion.

**Comment by wangdahoo** [comment]
add a demo link in README now.
