### ISSUE TITLE
How to access instance methods

### ISSUE THREAD

**Issue by OmranAbazid** [wangdahoo/vswipe#8]
Hi, 

I am a little bit new to Vuejs
I am trying to access Vswipe instance methods especially getpos() and getNum() of slides because want to add small circles at the bottom for navigation like other sliders.

I tried to use this.$refs but it returns undefined and then inject the element later.

Thanks

**Comment by devmount** [comment]
You need to notate a `ref` attribute, i.e.:

```
<swipe ref="mySwipe" :options="swipeOptions">
   ...
</swipe>
```

Then you can access this instance like this:

    this.$refs.mySwipe.getNum()
